@baseUrl = http://localhost:6001/api/profiles
@id=6751d86406b8509f92d00a6c
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzRmMDgzMTlkYjVmMWY3MTIwYjg3ZWUiLCJpYXQiOjE3MzM2ODQ2ODUsImV4cCI6MTczMzY5MTg4NX0.xkt8pjCmzra2Ovbb-KvFQoe5R2H3X7FtLoBegxd7VUg
###

GET {{baseUrl}}/candidates
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/employees?today=2024-12-09
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe",
  "email": "john.doe1@example.com",
  "phone": "123-456-7890",
  "position": "Software Engineer",
  "department": "Engineering",
  "experience": "3 years",
  "img": "profile-pic.jpg",               
  "status": "NEW",                
  "role": ""
}

###

GET {{baseUrl}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

PUT {{baseUrl}}/{{id}}
Content-Type: application/json

{
  "position": "Senior Software Engineer",
  "department": "Engineering"
}

###

PATCH {{baseUrl}}/{{id}}/status
Content-Type: application/json

{
  "status": "SELECTED"
}

###

PATCH {{baseUrl}}/{{id}}/role
Content-Type: application/json

{
  "role": "CANDIDATE"
}

###

PATCH {{baseUrl}}/{{id}}/attendance
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "ABSENT",
   "today": "2024-12-09"
}

###
PATCH {{baseUrl}}/{{id}}/task
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
  "task": "Complete the daily report",
  "today": "2024-12-09"
}
